### ISSUE TITLE
mismatch between number of total diseases and all therapeutic areas

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#103]
@elipapa commented on [Wed Aug 23 2017](https://github.com/opentargets/rest_api/issues/96)

ht/ @deniseOme:
When you look at the number of diseases associated with BRCA2:

![image](https://user-images.githubusercontent.com/112610/29626391-79662ba8-8826-11e7-84a5-be4f3b400c66.png)

and then select all facets:

![image](https://user-images.githubusercontent.com/112610/29626416-8c344ab2-8826-11e7-8cb4-28f2ae82f621.png)

you get two different numbers. 

Replicating the API calls used with `direct=false`
```sh
http 'https://api.targetvalidation.org/api/latest/public/association/filter?target=ENSG00000139618&outputstructure=flat&size=1000&direct=false&facets=false&therapeutic_area=efo_0000616&therapeutic_area=efo_0000508&therapeutic_area=efo_0000512&therapeutic_area=efo_0001379&therapeutic_area=other&therapeutic_area=efo_0000405&therapeutic_area=efo_0000701&therapeutic_area=efo_0000618&therapeutic_area=efo_0005803&therapeutic_area=efo_0003966&therapeutic_area=efo_0000684&therapeutic_area=efo_0000651&therapeutic_area=efo_0000540&therapeutic_area=efo_0002461&therapeutic_area=efo_0000524&therapeutic_area=efo_0000319&therapeutic_area=efo_0000589&therapeutic_area=efo_0005741&therapeutic_area=efo_0001421&therapeutic_area=efo_0003086&therapeutic_area=efo_1000018&therapeutic_area=efo_0001444&therapeutic_area=go_0008150' | jq '.total'
```
gives 328

with `direct=true`
```sh
http 'https://api.targetvalidation.org/api/latest/public/association/filter?target=ENSG00000139618&outputstructure=flat&size=1000&direct=true&facets=false&therapeutic_area=efo_0000616&therapeutic_area=efo_0000508&therapeutic_area=efo_0000512&therapeutic_area=efo_0001379&therapeutic_area=other&therapeutic_area=efo_0000405&therapeutic_area=efo_0000701&therapeutic_area=efo_0000618&therapeutic_area=efo_0005803&therapeutic_area=efo_0003966&therapeutic_area=efo_0000684&therapeutic_area=efo_0000651&therapeutic_area=efo_0000540&therapeutic_area=efo_0002461&therapeutic_area=efo_0000524&therapeutic_area=efo_0000319&therapeutic_area=efo_0000589&therapeutic_area=efo_0005741&therapeutic_area=efo_0001421&therapeutic_area=efo_0003086&therapeutic_area=efo_1000018&therapeutic_area=efo_0001444&therapeutic_area=go_0008150' | jq '.total'
```
gives 311

but omitting the therapeutic areas gives:
```sh
http 'https://api.targetvalidation.org/api/latest/public/association/filter?target=ENSG00000139618&outputstructure=flat&size=1000&direct=true&facets=false' | jq '.total'
```
gives 315

Saving the two lists and comparing them:
```sh
http 'https://api.targetvalidation.org/api/latest/public/association/filter?target=ENSG00000139618&outputstructure=flat&size=1000&direct=true&facets=false' | jq '.data[] | .disease.id' > brca315

http 'https://api.targetvalidation.org/api/latest/public/association/filter?target=ENSG00000139618&outputstructure=flat&size=1000&direct=true&facets=false&therapeutic_area=efo_0000616&therapeutic_area=efo_0000508&therapeutic_area=efo_0000512&therapeutic_area=efo_0001379&therapeutic_area=other&therapeutic_area=efo_0000405&therapeutic_area=efo_0000701&therapeutic_area=efo_0000618&therapeutic_area=efo_0005803&therapeutic_area=efo_0003966&therapeutic_area=efo_0000684&therapeutic_area=efo_0000651&therapeutic_area=efo_0000540&therapeutic_area=efo_0002461&therapeutic_area=efo_0000524&therapeutic_area=efo_0000319&therapeutic_area=efo_0000589&therapeutic_area=efo_0005741&therapeutic_area=efo_0001421&therapeutic_area=efo_0003086&therapeutic_area=efo_1000018&therapeutic_area=efo_0001444&therapeutic_area=go_0008150' | jq '.data[] | .disease.id' >brca311

sort brca315 brca311  |uniq -u    

```
Shows that these are the culprit:
```sh                                                                                                            
"EFO_0000319"
"EFO_0000508"
"EFO_0000616"
"EFO_0003086"
```

@gkos-bio is this an EFO problem?

---

@ElaineMcA commented on [Tue Aug 28 2018](https://github.com/opentargets/rest_api/issues/96#issuecomment-416509061)

@gkos-bio Can you please check if this is still happening with 18.08?  if so, what to do to resolve please?  Specific points will help here.

**Comment by ElaineMcA** [comment]
Checked 30Aug2018: Resolved in UI.

![screen shot 2018-08-30 at 15 28 58](https://user-images.githubusercontent.com/40168275/44858502-11cda200-ac6a-11e8-9968-e61de6abd9f7.png)
![screen shot 2018-08-30 at 15 29 28](https://user-images.githubusercontent.com/40168275/44858509-15f9bf80-ac6a-11e8-985a-8e52faf06a4c.png)

**Comment by deniseOme** [comment]
It's still happening in 18.08.

1) 387 diseases associated with BRCA2, without changing anything in the facet "Therapeutic areas".

![screencapture-targetvalidation-org-target-ensg00000139618-associations-2018-08-30-15_57_12](https://user-images.githubusercontent.com/6472381/44860104-72121300-ac6d-11e8-8880-29c74033a1d0.png)

2) 381 diseases associated with BRCA2 when selecting all fields in the facet "Therapeutic areas".

![screencapture-targetvalidation-org-target-ensg00000139618-associations-2018-08-30-15_58_28](https://user-images.githubusercontent.com/6472381/44860177-9110a500-ac6d-11e8-998c-597f563007ee.png)

As far as the API call goes, the following will return 387 diseases:

> `https://api.opentargets.io/v3/platform/public/association/filter?target=ENSG00000139618&size=1000&direct=true`

whereas the next URL will return 23 results:

`https://api.opentargets.io/v3/platform/public/association/filter?target=ENSG00000139618&size=1000&direct=false&therapeutic_area=efo_0000616&therapeutic_area=efo_0000508&therapeutic_area=efo_0000512&therapeutic_area=efo_0001379&therapeutic_area=other&therapeutic_area=efo_0000405&therapeutic_area=efo_0000701&therapeutic_area=efo_0000618&therapeutic_area=efo_0005803&therapeutic_area=efo_0003966&therapeutic_area=efo_0000684&therapeutic_area=efo_0000651&therapeutic_area=efo_0000540&therapeutic_area=efo_0002461&therapeutic_area=efo_0000524&therapeutic_area=efo_0000319&therapeutic_area=efo_0000589&therapeutic_area=efo_0005741&therapeutic_area=efo_0001421&therapeutic_area=efo_0003086&therapeutic_area=efo_1000018&therapeutic_area=efo_0001444`

Presumably, 23 = 21 EFO IDs + other (see list below) + 1 I could not locate:

efo_0000616
efo_0000508
efo_0000512
efo_0001379
efo_0000405
efo_0000701
efo_0000618
efo_0005803
efo_0003966
efo_0000684
efo_0000651
efo_0000540
efo_0002461
efo_0000524
efo_0000319
efo_0000589
efo_0005741
efo_0001421
efo_0003086
efo_1000018
efo_0001444
other
???? (missing)

I'm assuming these EFOs are = the therapeutic areas selected in the UI in the TA facet (see item 2 above).

The 4 offending EFOs highlighted by @elipapa are:
- cardiovascular disease
- genetic disorder
- neoplasm
- kidney disease

Neoplasm is a TA (therapeutic area) but not a disease in the associations page.
Same applies for cardiovascular and kidney diseases and genetic disorder.

Maybe it's not a bug after all; rather an unpleasant feature.

Cardiovascular disease, genetic disorder, neoplasm, and kidney disease are counted as diseases when facets are not selected, but them discounted when facets are selected.

**Comment by d0choa** [comment]
No work is expected in this ticket for the current API
