### ISSUE TITLE
Target ENSG00000164181 duplicated in the 21.06 json data

### ISSUE THREAD

**Issue by fedde-s** [opentargets/platform#1738]
This may have already been resolved in work towards post-21.06 releases, but I found that [`21.06/output/etl/json/targets/part-00023-[…].json`](https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/21.06/output/etl/json/targets/part-00023-d9b064a1-a213-4da8-a42d-7c2521e24e47-c000.json) listed the gene ELOVL7 twice, with this difference:
```json
"tep":{"uri":"https://www.thesgc.org/tep/elovl7","name":"ELOVL7"}
"tep":{"uri":"https://www.thesgc.org/tep/elovl7","name":"DHTKD1"}
```

Given that these have the same gene ID (document ID in Elasticsearch), I believe that the latter overwrites the former in Elasticsearch, and shows up in the TEP section on https://platform.opentargets.org/target/ENSG00000164181.

The target is also duplicated in `21.06/output/etl/json/searchTarget/part-00083-[…].json`, but those two lines are identical and both loaded (to an index that doesn't use a field as the document id).

**Comment by fedde-s** [comment]
Apologies if this is already resolved or not an issue!

**Comment by d0choa** [comment]
Thanks, @fedde-s for reporting. I made a few checks on the upcoming target (21.09) and the problem is still there. In fact, there are 3 targets with repeated entries and the same `id` field. 

```
>>> target.groupBy("id").count().sort(F.col("count").desc()).show(5)
+---------------+-----+                                                         
|             id|count|
+---------------+-----+
|ENSG00000230417|    2|
|ENSG00000164181|    2|
|ENSG00000254876|    2|
|ENSG00000023697|    1|
|ENSG00000033800|    1|
+---------------+-----+
only showing top 5 rows
```

The problem with `ELOVL7` seems to be related to an unnecessary explosion of the `tep` field and it's inherited from 21.06:

```
>>> target.filter(F.col("id") == "ENSG00000164181").select("id", "approvedSymbol", "tep").show(vertical = True, truncate = False)
-RECORD 0-----------------------------------------------------                  
 id             | ENSG00000164181                             
 approvedSymbol | ELOVL7                                      
 tep            | {DHTKD1, https://www.thesgc.org/tep/elovl7} 
-RECORD 1-----------------------------------------------------
 id             | ENSG00000164181                             
 approvedSymbol | ELOVL7                                      
 tep            | {ELOVL7, https://www.thesgc.org/tep/elovl7} 
```

The other 2 offending cases (ENSG00000230417 and ENSG00000254876) are newly introduced in the new target object. They have 2 different `approvedSymbols`, so it could be caused by an explosion in this field:

```
>>> target.filter(F.col("id") == "ENSG00000230417").select("id", "approvedSymbol", "tep").show(vertical = True, truncate = False)
-RECORD 0-------------------------                                              
 id             | ENSG00000230417 
 approvedSymbol | LINC00595       
 tep            | null            
-RECORD 1-------------------------
 id             | ENSG00000230417 
 approvedSymbol | LINC00856       
 tep            | null            
 ```

```
>>> target.filter(F.col("id") == "ENSG00000254876").select("id", "approvedSymbol", "tep").show(vertical = True, truncate = False)
-RECORD 0-------------------------                                              
 id             | ENSG00000254876 
 approvedSymbol | SUGT1P4-STRA6LP 
 tep            | null            
-RECORD 1-------------------------
 id             | ENSG00000254876 
 approvedSymbol | STRA6LP         
 tep            | null            
```

We should stick to the premise of no repeated IDs in the entity datasets.

**Comment by JarrodBaker** [comment]
The two additional entries identified by @d0choa were caused by duplicate entries in the HGNC input file. 

The issue identified by @fedde-s is caused by the TEP input file itself:

```
+---------------+--------------+------------------------------------------+
|Ensembl_id     |OT_Target_name|URI                                       |
+---------------+--------------+------------------------------------------+
|ENSG00000164181|DHTKD1        |https://www.thesgc.org/tep/elovl7         |
|ENSG00000164181|ELOVL7        |https://www.thesgc.org/tep/elovl7         |
```
Is the TEP input file something that we curate @d0choa ?

**Comment by ireneisdoomed** [comment]
The duplication error is indeed coming from an obsolete version of the TEPs dataset. I've opened a ticket to address this discrepancy and pull the new version (#1742).
