### ISSUE TITLE
EPMC: filter problematic disease synonyms introduced through switch from EFO2 to EFO3

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/platform#574]
The dictionary used by EPMC for text mining target-disease associations is updated whenever EFO is updated. The change from EFO2 to EFO3 resulted in a marked increase in disease labels (synonyms):

  | 19.02 | 19.04
-- | -- | --
nr of disease IDs | 5,942 | 6,486
nr of disease labels | 27,846 | 41,667

Some of these 'new' labels are very generic and frequent terms and should be removed from the disease dictionary. The label 'was' for example, has 4.5 mio associations in the 19.04 EPMC data. Open Targets and EPMC will work through the list of disease labels compiled [here](https://docs.google.com/spreadsheets/d/13OjyDOsYWREiJqA6zSAr-d3d61IZRu7o0BfTcIFIDBU/edit#gid=0) (together with association counts).

**Comment by MichaelaEBI** [comment]
**More details, July 17, 2019:**
epmc text mining is based on dictionaries and the disease dictionary (containing synonyms and acronyms of diseases mapped to IDs) has doubled in size from EFO2 to EFO3: 32,821 vs 72,510 entries respectively (above we can see that only ~28,000 and ~42,000 disease labels are actually found by the text mining pipeline). After the initial data submission that used the EFO3 dictionary, a few terms have been identified that should be blacklisted because they lead to mostly false positive text mining hits. So far, the following terms have been identified as problematic in the new EFO3 dictionary: "can", "was", "sensitivity", "sensitive", "fed", "men", "gave", "allergic", "mono", "fracture", "fractures", "arms", "burn", "chi", "sensitivities", "era", "pad"

EPMC generates EFO dictionaries from the OWL file from the EFO website to issue SPARQL queries. Labels and `hasExactSynonym` matches are used. Currently the rules for EFO dictionary generation are the following:
```
Regarding the EFO dictionary generation, these are the performed steps:

1. the following words are stripped from each term if they are there : ['(morphologic abnormality)','(finding)','[Ambiguous]']
2. if the term contains one of the Greek letters in the form ['Alpha','Beta,'Gamma','Delta'], an additional term will be added with the corresponding short form [α,β,γ,δ]
3. if the  term contains the word (disorder) two terms will be added: one with the word disorder and one with the word disorder stripped
4. The blacklist terms are:
    id="EFO_0000545" and term == "sterile"
    id == "EFO_0001365" and term == "Amended"
    Recently for EFO 3 we added the following terms to the blacklist :  ["can","was","sensitivity","sensitive","fed","men","gave","allergic","mono","fracture","fractures","arms","burn","chi","sensitivities","era","pad"]
```
We now have the dictionaries for EFO2 and EFO3 in TSV format and these should be reviewed to assess the difference between the two EFO versions and identify further potentially problematic terms.

**Comment by MichaelaEBI** [comment]
We need an efficient strategy to prune the EFO3 dictionary, it is impossible to go through >70,000 terms manually. We can reduce the number of terms to look at by
- Looking at how frequently disease terms are found together with gene names (as done [here](https://docs.google.com/spreadsheets/d/13OjyDOsYWREiJqA6zSAr-d3d61IZRu7o0BfTcIFIDBU/edit#gid=0)) and curate the list starting with the most frequent terms. Problematic terms like the one identified above ("can" for example) are likely to appear very often.
- Focussing on short terms - many problematic terms identified above have 3 or 4 letters only.

The EFO3 dictionary was used for the April data submission, but MONDO IDs did not work with their pipeline at that time. It probably makes sense to ask epmc to re-run the pipeline now with the EFO3 dictionary to generate a complete frequency table (including MONDO IDs and their labels).

**Comment by iandunham** [comment]
What we could do is to split the task on the 70000 and go through sets of around 1000  each starting at the most frequent. 

By the way there was some previous work that I did on this for Senay's pipeline in two ways. The first is identifying FP disease terms in general analogous to the first approach
[EFO_terms_Freq_OASet.xlsx](https://github.com/opentargets/platform/files/3406656/EFO_terms_Freq_OASet.xlsx)

**Comment by iandunham** [comment]
The second is analysis of short term FP examples which Senay did, I think, and is the basis for the post processing filtering of the literature evidence (or at least part of it). In this file there is a set of disease abbreviations and an automatic analysis of FPs, which then has a comment after tehm if they are in fact TPs.
[DisAbbrClassification.xlsx](https://github.com/opentargets/platform/files/3406666/DisAbbrClassification.xlsx)

**Comment by AsierGonzalez** [comment]
EPMC have ran their pipeline with EFO3 and this needs to be updated with current status before the next steps are decided.

**Comment by AsierGonzalez** [comment]
Preliminary checks suggested that although the number of associations is still high in EFO3 compared to EFO2, the issues with common words being tagged as targets or disease has been solved. Therefore, it has been decided that the data pipeline will be run with 19.09 data and EFO3 to perform more detailed testing.

**Comment by d0choa** [comment]
Although the problem might still persist at a lower extent, we can close this issue. We'll keep an eye on problematic synonyms in the future.
